# Generated by Selenium IDE
# Imported libraries and packages
import pytest                                                        # Test framework
import time                                                          # Time control
import json                                                          # Read and Write in json format
# Import selenium libraries 4.1.0
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConsultarPython():
    def setup_method(self, method):
        # Instantiate the object WebDriver as Chrome
        self.driver = webdriver.Chrome('C:/Users/Vitor/Desktop/Vitor/Cursos/Python2023/PyIterasys/driver/114/chromedriver.exe')
        self.driver.implicitly_wait(30)     # Wait for 30 seconds for the web elements
        self.driver.maximize_window()       # Maximize window
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_consultarPython(self):
        self.driver.get("https://iterasys.com.br/pt")
        self.driver.find_element(By.CSS_SELECTOR, "#\\31 6237702146520 > .item-pill").click()
        self.driver.find_element(By.ID, "auto-i-5020083214233075").click()
        self.driver.find_element(By.ID, "auto-i-5020083214233075").send_keys("Python")
        self.driver.find_element(By.CSS_SELECTOR, ".content-card-cover > .bg-img").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "h1:nth-child(1)").text == "Introdução ao Python"
        assert self.driver.find_element(By.CSS_SELECTOR, ".content-purchase-info:nth-child(2) p").text == "R$ 27,90"